platform :ios, '11.0'

target 'moyo-ceshi-01' do

#pod 'Moya'
#, '~> 13.0.1'
pod 'ObjectMapper', '~> 3.4'
pod 'DGElasticPullToRefresh'
pod 'KRProgressHUD'
pod 'PKHUD', '~> 5.0'

pod 'CryptoSwift'
pod 'Alamofire', '~> 5.0.0-beta.5'



end

