platform :ios, '10.0'

target 'moyo-ceshi-01' do
use_frameworks!

pod 'ObjectMapper', '~> 3.4'
pod 'DGElasticPullToRefresh'
pod 'KRProgressHUD'
pod 'PKHUD', '~> 5.0'

pod 'CryptoSwift'
pod 'SnapKit', '~> 5.0.0'
pod 'Socket.IO-Client-Swift', '~> 15.1.0'
pod 'CocoaMQTT'
pod 'CocoaAsyncSocket'
pod 'Alamofire'


end

